CREATE DATABASE QuanLyQuanNhau
GO

USE QuanLyQuanNhau
GO

-- Food
-- Table
-- FoodCategory
-- Account
-- Bill
-- BillInfo

CREATE TABLE TABLEFOOD
(
	TABLEFOOD_ID INT IDENTITY PRIMARY KEY,
	TABLEFOOD_NAME NVARCHAR(100) NOT NULL DEFAULT N'Bàn chưa có tên',
	TABLEFOOD_STATUS NVARCHAR(100) NOT NULL DEFAULT N'Trống',
)
GO

CREATE TABLE ACOUNT
(
	ACOUNT_USERNAME NVARCHAR(100) PRIMARY KEY,
	ACOUNT_DISPLAYNAME NVARCHAR(100) NOT NULL,
	ACOUNT_PASSWORD NVARCHAR(100) NOT NULL,
	ACOUNT_TYPE INT NOT NULL DEFAULT 0,  --0:staff && 1:admin
)
GO

CREATE TABLE FOODCATEGORY
(
	FOODCATEGORY_ID INT IDENTITY PRIMARY KEY,
	FOODCATEGORY_NAME NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
)
GO

CREATE TABLE FOOD
(
	FOOD_ID INT IDENTITY PRIMARY KEY,
	FOOD_NAME NVARCHAR(1000) NOT NULL DEFAULT N'Chưa đặt tên',
	FOOD_IDCATEGORY INT NOT NULL,
	FOOD_PRICE FLOAT NOT NULL,

	FOREIGN KEY (FOOD_IDCATEGORY) REFERENCES dbo.FOODCATEGORY(FOODCATEGORY_ID),
)
GO

CREATE TABLE BILL
(
	BILL_ID INT IDENTITY PRIMARY KEY,
	BILL_DATECHECKIN DATETIME NOT NULL DEFAULT GETDATE(),
	BILL_DATECHECKOUT DATETIME,
	BILL_IDTABLE INT NOT NULL,
	BILL_STATUS INT NOT NULL DEFAULT 0, --0:chưa thanh toán && 1:dã thanh toán

	FOREIGN KEY (BILL_IDTABLE) REFERENCES dbo.TABLEFOOD(TABLEFOOD_ID)
)
GO

CREATE TABLE BILLINFO
(
	BILLINFO_ID INT IDENTITY PRIMARY KEY,
	BILLINFO_IDBILL INT NOT NULL,
	BILLINFO_IDFOOD INT NOT NULL,
	COUNT INT NOT NULL DEFAULT 0,

	FOREIGN KEY (BILLINFO_IDBILL) REFERENCES dbo.BILL(BILL_ID),
	FOREIGN KEY (BILLINFO_IDFOOD) REFERENCES dbo.FOOD(FOOD_ID)
)
GO

USE QuanLyQuanNhau
INSERT INTO dbo.ACOUNT
(
    ACOUNT_USERNAME,
    ACOUNT_DISPLAYNAME,
    ACOUNT_PASSWORD,
    ACOUNT_TYPE
)
VALUES
(   N'admin',    -- ACOUNT_USERNAME - nvarchar(100)
    N'ADMIN',    -- ACOUNT_DISPLAYNAME - nvarchar(100)
    N'admin',    -- ACOUNT_PASSWORD - nvarchar(100)
    1 -- ACOUNT_TYPE - int
    )

INSERT INTO dbo.ACOUNT
(
    ACOUNT_USERNAME,
    ACOUNT_DISPLAYNAME,
    ACOUNT_PASSWORD,
    ACOUNT_TYPE
)
VALUES
(   N'staff',    -- ACOUNT_USERNAME - nvarchar(100)
    N'STAFF',    -- ACOUNT_DISPLAYNAME - nvarchar(100)
    N'staff',    -- ACOUNT_PASSWORD - nvarchar(100)
    0 -- ACOUNT_TYPE - int
    )

SELECT *FROM dbo.ACOUNT

SELECT * FROM dbo.ACOUNT WHERE ACOUNT_USERNAME LIKE N'" + userName"' AND ACOUNT_PASSWORD LIKE N'" + passWord +"'
